<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $courses = $this->getCoursesData();

        foreach ($courses as $course) {
            Course::create($course);
        }
    }

    protected function getCoursesData()
    {
        return [
            [
                "code" => "IT 111",
                "course" => "Introduction to Computing",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "GEd 102",
                "course" => "Mathematics in the Modern World",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "GEd 108",
                "course" => "Art Appreciation",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Fili 101",
                "course" => "Kontekstwalisadong Komunikasyon sa Filipino",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "PE 101",
                "course" => "Physical Fitness, Gymnastics and Aerobics",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "NSTP 111",
                "course" => "National Service Training Program 1",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "GEd 103",
                "course" => "The Life and Works of Rizal",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "GEd 104",
                "course" => "The Contemporary World",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 111",
                "course" => "Computer Programming",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 131",
                "course" => "Data Structures and Algorithms",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "MATH 111",
                "course" => "Linear Algebra",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Fili 102",
                "course" => "Filipino sa Iba't-ibang Disiplina",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "GEd 105",
                "course" => "Readings in Philippine History",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "GEd 109",
                "course" => "Science, Technology and Society",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "PE 102",
                "course" => "Rhythmic Activities",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "NSTP 121",
                "course" => "National Service Training Program 2",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 121",
                "course" => "Advanced Computer Programming",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 211",
                "course" => "Database Management System",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 211",
                "course" => "Object-Oriented Programming",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "Litr 102",
                "course" => "ASEAN Literature",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 405",
                "course" => "Discrete Mathematics",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Phy 101",
                "course" => "Calculus-Based Physics",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 212",
                "course" => "Computer Networking 1",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "PE 103",
                "course" => "Individual and Dual Sports",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 221",
                "course" => "Information Management",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 223",
                "course" => "Computer Networking 2",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 222",
                "course" => "Advanced Database Management System",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "MATH 408",
                "course" => "Data Analysis",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ES 101",
                "course" => "Environmental Sciences",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "GEd 106",
                "course" => "Purposive Communication",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "GEd 101",
                "course" => "Understanding the Self",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "PE 104",
                "course" => "Team Sports",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 311",
                "course" => "Systems Administration and Maintenance",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 312",
                "course" => "Systems Integration and Architecture",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "NTT 401",
                "course" => "Computer Networking 3",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "NTT 402",
                "course" => "Internet of Things (IoT)",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 313",
                "course" => "System Analysis and Design",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 314",
                "course" => "Web Systems and Technologies",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "GEd 107",
                "course" => "Ethics",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 321",
                "course" => "Human-Computer Interaction",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "NTT 403",
                "course" => "Computer Networking 4",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "NTT 404",
                "course" => "Cloud Computing",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 322",
                "course" => "Advanced Systems Integration and Architecture",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 323",
                "course" => "Information Assurance and Security",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 324",
                "course" => "Capstone Project 1",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 325",
                "course" => "IT Project Management",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 331",
                "course" => "Application Development and Emerging Technologies",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 332",
                "course" => "Integrative Programming and Technologies",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 423",
                "course" => "Social Issues and Professional Practice",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 411",
                "course" => "Capstone Project 2",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "NTT 405",
                "course" => "Cybersecurity",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 405",
                "course" => "Technopreneurship",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 413",
                "course" => "Advanced Information Assurance and Security",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 414",
                "course" => "Systems Quality Assurance",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 412",
                "course" => "Platform Technologies",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 421",
                "course" => "IT Internship Training",
                "unit" => "6",
                "lecture" => "0",
                "laboratory" => "500",
            ],
            [
                "code" => "BAT 401",
                "course" => "Fundamentals of Business Analytics",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "BAT 402",
                "course" => "Fundamentals of Analytics Modeling",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "BAT 403",
                "course" => "Fundamentals of Enterprise Data Management",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "BAT 404",
                "course" => "Analytics Techniques & Tools",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "BAT 405",
                "course" => "Analytics Application",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "AST 111",
                "course" => "Math for Technology",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "AST 102",
                "course" => "Applied Chemistry",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "AST 105",
                "course" => "Applied Physics",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "AST 133",
                "course" => "Production Drawing ",
                "unit" => "2",
                "lecture" => "1",
                "laboratory" => "3",
            ],
            [
                "code" => "AST 129",
                "course" => "Electronics Measurements",
                "unit" => "2",
                "lecture" => "1",
                "laboratory" => "3",
            ],
            [
                "code" => "AST 112",
                "course" => "Electrical Principles",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "PM 101",
                "course" => "Occupational Health and Safety Management ",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "ELX 111",
                "course" => "Introduction to Semiconductor Devices",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "AST 135",
                "course" => "Computer Aided Design",
                "unit" => "2",
                "lecture" => "1",
                "laboratory" => "3",
            ],
            [
                "code" => "ELX 121",
                "course" => "Electronic Amplifiers and Integrated Circuits",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ELX 122",
                "course" => "Digital Logic Circuits and Switching",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "PM 102",
                "course" => "Industrial Operation & Management Practices",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "AST 134",
                "course" => "Computer Programming ",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "AST 120",
                "course" => "Programmable Logic Control",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ELX 211",
                "course" => "Electronics Workshop I",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ELX 212",
                "course" => "Industrial Electronics",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "PM 103",
                "course" => "Production and Operations Management",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "AST 110",
                "course" => "Data Analytics",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ELX 221",
                "course" => "Analog Communication Systems",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ELX 222",
                "course" => "Microcomputer Systems",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ELX 223",
                "course" => "Automatic Controls",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ELX 224",
                "course" => "Electronics Workshop II",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "PM 104",
                "course" => "Technology Research I",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "PM 105",
                "course" => "Materials Technology Management",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "PM 106",
                "course" => "Professional Ethics",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ELX 311",
                "course" => "Wireless and Satellite Communication Systems",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ELX 312",
                "course" => "Plant Safety Network",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "PM 107",
                "course" => "Technology Research II",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "PM 108",
                "course" => "Manufacturing Technology ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "PM 109",
                "course" => "Total Quality Management",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "PM 110",
                "course" => "Environmental Technology",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "PM 111",
                "course" => "Technopreneurship",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ELX 321",
                "course" => "Totally Integrated Automatic",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => " OJT 1 ",
                "course" => "Supervised Industrial Training 1 (540hrs)",
                "unit" => "10",
                "lecture" => "0",
                "laboratory" => "10",
            ],
            [
                "code" => " OJT 2 ",
                "course" => "Supervised Industrial Training 2 (540hrs)",
                "unit" => "10",
                "lecture" => "0",
                "laboratory" => "10",
            ],
            [
                "code" => "ACC 101",
                "course" => "Financial Accounting and Reporting 1 ",
                "unit" => "6",
                "lecture" => "6",
                "laboratory" => "0",
            ],
            [
                "code" => "MGT 303",
                "course" => "Operations Management with TQM ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MGT 207",
                "course" => "Human Behavior in Organizations ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 102",
                "course" => "Financial Accounting and Reporting 2 ",
                "unit" => "6",
                "lecture" => "6",
                "laboratory" => "0",
            ],
            [
                "code" => "ECO 310",
                "course" => "Economic Development ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MGT 406",
                "course" => "Strategic Management ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 101",
                "course" => "IT Application Tools in Business ",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ACC 203",
                "course" => "Conceptual Framework and Accounting Standards ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 204",
                "course" => "Cost Accounting and Control ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "LAW 201",
                "course" => "Law on Obligations and Contracts ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MGT 208",
                "course" => "Management Science ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MGT 209",
                "course" => "Governance, Business Ethics, Risk Management and Internal Control ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "GEd 109",
                "course" => "Science, Technology, and Society ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 205",
                "course" => "Intermediate Accounting 1 ",
                "unit" => "6",
                "lecture" => "6",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 206",
                "course" => "Strategic Cost Management ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 207",
                "course" => "Accounting Information System ",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "LAW 202",
                "course" => "Law on Business Organizations ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 308",
                "course" => "Strategic Business Analysis ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 309",
                "course" => "Intermediate Accounting 2 ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 310",
                "course" => "Auditing and Assurance Principles ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "TAX 301",
                "course" => "Income Taxation ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 311",
                "course" => "Accounting for Special Transactions and Business Combinations",
                "unit" => "6",
                "lecture" => "6",
                "laboratory" => "0",
            ],
            [
                "code" => "ECO 307",
                "course" => "Managerial Economics ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "STS 301",
                "course" => "Statistical Analysis with Software Application ",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 313",
                "course" => "Auditing and Assurance Concepts and Applications",
                "unit" => "6",
                "lecture" => "6",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 312",
                "course" => "Accounting for Government and Non-profit Organizations ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 315",
                "course" => "Research Methods Applied in Accountancy ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "RFB 301",
                "course" => "Regulatory Framework and Legal Issues in Business ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "TAX 302",
                "course" => "Business and Transfer Taxes ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "FM 101",
                "course" => "Financial Management ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 314",
                "course" => "Operations Auditing ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 417",
                "course" => "Accounting Internship (400 hrs) ",
                "unit" => "6",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 416",
                "course" => "Accountancy Thesis Writing ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 418",
                "course" => "Accountancy Refresher with Comprehensive Exam ",
                "unit" => "6",
                "lecture" => "6",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 419",
                "course" => "Updates in Financial Accounting and Reporting Standards ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 420",
                "course" => "Auditing and Assurance: Specialized Industries ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "FM 415",
                "course" => "Financial Markets ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MGT 304",
                "course" => "International Business and Trade ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ACC 421",
                "course" => "Auditing in a CIS Environment",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "MGT 410",
                "course" => "Valuation Concepts and Methods",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 111",
                "course" => "Computer Programming",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "Math 111",
                "course" => "Linear Algebra",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 121",
                "course" => "Advanced Computer Programming",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "Math 401",
                "course" => "Differential Calculus",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Math 407",
                "course" => "Number Theory",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 131",
                "course" => "Data Structures and Algorithms",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "Math 402",
                "course" => "Integral Calculus",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 211",
                "course" => "Object-Oriented Programming",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 212",
                "course" => "Computer Organization w\/ Assembly Language",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 211",
                "course" => "Database Management Systems",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "Phy 101",
                "course" => "Calculus-Based Physics",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 405",
                "course" => "Discrete Mathematics",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 221",
                "course" => "Design and Analysis of Algorithms",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 222",
                "course" => "Advanced Object-Oriented Programming",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ES 101",
                "course" => "Environmental Sciences",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 414",
                "course" => "Numerical Methods",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 311",
                "course" => "Automata Theory and Formal Languages",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 312",
                "course" => "Mobile Computing",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 321",
                "course" => "Human Computer Interaction",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 314",
                "course" => "Web Systems and Technologies",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "IT 331",
                "course" => "Application Development and Emerging Technologies",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "Math 408",
                "course" => "Data Analysis",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 321",
                "course" => "Programming Languages",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 322",
                "course" => "Software Engineering",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 323",
                "course" => "Computer Architecture",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 324",
                "course" => "Modeling and Simulation",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CSE 1",
                "course" => "CS Professional Elective 1",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "Math 409",
                "course" => "Symbolic Logic",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 331",
                "course" => "CS Internship",
                "unit" => "3",
                "lecture" => "0",
                "laboratory" => "162",
            ],
            [
                "code" => "CS 411",
                "course" => "CS Thesis 1",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 412",
                "course" => "Fundamentals of Data Science",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 413",
                "course" => "Advanced Software Engineering",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 414",
                "course" => "Artificial Intelligence",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 415",
                "course" => "Principles of Operating Systems",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CSE 2",
                "course" => "CS Professional Elective 2",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 421",
                "course" => "CS Thesis 2",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CS 422",
                "course" => "Machine Learning",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CS 423",
                "course" => "Social Issues and Professional Practice",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "IT 323",
                "course" => "Information Assurance and Security",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 405",
                "course" => "Technopreneurship",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CPE 3",
                "course" => "CS Professional Elective 3",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 401",
                "course" => "Introduction to Engineering",
                "unit" => "1",
                "lecture" => "0",
                "laboratory" => "3",
            ],
            [
                "code" => "MATH 401",
                "course" => "Differential Calculus",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "SCI 401",
                "course" => "General Chemistry",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 401",
                "course" => "Computer Programming 1",
                "unit" => "1",
                "lecture" => "0",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 402",
                "course" => "Engineering Drawing",
                "unit" => "1",
                "lecture" => "0",
                "laboratory" => "3",
            ],
            [
                "code" => "MATH 402",
                "course" => "Integral Calculus",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "SCI 403",
                "course" => "Physics 1",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "SCI 402",
                "course" => "Modern Biology",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 403",
                "course" => "Computer Engineering as a Discipline",
                "unit" => "1",
                "lecture" => "1",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 404",
                "course" => "Programming Logic and Design",
                "unit" => "2",
                "lecture" => "0",
                "laboratory" => "6",
            ],
            [
                "code" => "CpE 405",
                "course" => "Discrete Mathematics",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "EE 423",
                "course" => "Fundamentals of Electrical Engineering",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 403",
                "course" => "Computer-Aided Design",
                "unit" => "1",
                "lecture" => "0",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 404",
                "course" => "Engineering Economics",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MATH 403",
                "course" => "Engineering Data Analysis",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MATH 404",
                "course" => "Differential Equations",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 406",
                "course" => "Object Oriented Programming",
                "unit" => "2",
                "lecture" => "0",
                "laboratory" => "6",
            ],
            [
                "code" => "CpE 407",
                "course" => "CpE Laws and Professional Practice",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 408",
                "course" => "Advanced Engineering Mathematics for CpE",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpEE 401",
                "course" => "Cognate\/Elective Course 1",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ECE 421",
                "course" => "Electronic Circuits: Devices and Analysis",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 411",
                "course" => "Basic Occupational Health and Safety",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ENGG 414",
                "course" => "Numerical Methods",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 410",
                "course" => "Logic Circuits and Design",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 411",
                "course" => "Data Structures and Algorithms",
                "unit" => "2",
                "lecture" => "0",
                "laboratory" => "6",
            ],
            [
                "code" => "CpE 412",
                "course" => "Introduction to Networks, Data and Digital Communications (CISCO 1)",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 413",
                "course" => "Fundamentals of Mixed Signals and Sensors",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 414",
                "course" => "Feedback and Control Systems",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 415",
                "course" => "Introduction to HDL",
                "unit" => "1",
                "lecture" => "0",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 416",
                "course" => "Research Methods",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 417",
                "course" => "Microprocessors",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 418",
                "course" => "Software Design",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 419",
                "course" => "Routing and Switching (CISCO 2)",
                "unit" => "1",
                "lecture" => "0",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 420",
                "course" => "Digital Signal Processing",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 421",
                "course" => "Emerging Technologies in CpE",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 422",
                "course" => "CpE Practice and Design 1",
                "unit" => "1",
                "lecture" => "0",
                "laboratory" => "3",
            ],
            [
                "code" => "CpEE 402",
                "course" => "Cognate\/Elective Course 2",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 423",
                "course" => "Scaling Networks (CISCO 3)",
                "unit" => "1",
                "lecture" => "0",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 424",
                "course" => "Operating Systems",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpE 425",
                "course" => "Computer Architecture and Organization",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 426",
                "course" => "Computer Engineering Drafting and Design",
                "unit" => "1",
                "lecture" => "0",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 427",
                "course" => "Connecting Networks and Security (CISCO 4)",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 428",
                "course" => "Embedded Systems",
                "unit" => "4",
                "lecture" => "3",
                "laboratory" => "3",
            ],
            [
                "code" => "CpE 429",
                "course" => "Seminars and Fieldtrips",
                "unit" => "2",
                "lecture" => "0",
                "laboratory" => "6",
            ],
            [
                "code" => "IE 425",
                "course" => "Manufacturing and Quality Control",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CpEE 403",
                "course" => "Cognate\/Elective Course 3",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "3",
            ],
            [
                "code" => "ENGG 405",
                "course" => "Technopreneurship",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "ENGG 417",
                "course" => "On-the-Job Training",
                "unit" => "4",
                "lecture" => "0",
                "laboratory" => "320",
            ],
            [
                "code" => "CpE 430",
                "course" => "CpE Practice and Design 2",
                "unit" => "2",
                "lecture" => "0",
                "laboratory" => "6",
            ],
            [
                "code" => "CRIM 101",
                "course" => "Introduction to Criminology",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CDI 101",
                "course" => "Fundamentals of Criminal Investigation and Intelligence",
                "unit" => "4",
                "lecture" => "4",
                "laboratory" => "0",
            ],
            [
                "code" => "LITR 101",
                "course" => "Sosyedad at Literatura\/ Panitikang Panlipunan",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "DEF TACT 101",
                "course" => "Fundamentals of Martial Arts",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "NSTP 101",
                "course" => "National Service Training Program 1",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CRIM 102",
                "course" => "Professional Conduct and Ethical Standards",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CRIM 103",
                "course" => "Theories of Crime Causation",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "LEA 101",
                "course" => "Law Enforcement Organization and Administration (Inter-agency Approach)",
                "unit" => "4",
                "lecture" => "4",
                "laboratory" => "0",
            ],
            [
                "code" => "DEF TACT 102",
                "course" => "Arnis and Disarming Techniques",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "NSTP 102",
                "course" => "National Service Training Program 2",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "FILI 103",
                "course" => "Retorikia - Masining na Pagpapahayag",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CHEM 106",
                "course" => "General Chemistry (Organic)",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "1",
            ],
            [
                "code" => "CLJ 101",
                "course" => "Introduction to Philippine Criminal Justice System",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "LEA 102",
                "course" => "Law Enforcement Operations and Planning with Crime Mapping",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CDI 102",
                "course" => "Technical English 1 (Investigative Report Writing and Presentation)",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "FORENSIC 101",
                "course" => "Forensic Photography",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "1",
            ],
            [
                "code" => "LEA 103",
                "course" => "Comparative Models of Policing",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CA 101",
                "course" => "Institutional Corrections",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CLJ 102",
                "course" => "Criminal Law (Book 1)",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CDI 103",
                "course" => "Technical English 2 (Legal Forms)",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CRIM 104",
                "course" => "Human Behavior and Victimology",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "OJT",
                "course" => "On-the-Job Training & Community Immersion (270 hrs.)",
                "unit" => "3",
                "lecture" => "0",
                "laboratory" => "0",
            ],
            [
                "code" => "FORENSIC 102",
                "course" => "Personal Identification Techniques",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "1",
            ],
            [
                "code" => "CA 102",
                "course" => "Non-Institutional Corrections",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CLJ 103",
                "course" => "Criminal Law (Book 2)",
                "unit" => "4",
                "lecture" => "4",
                "laboratory" => "0",
            ],
            [
                "code" => "CDI 104",
                "course" => "Specialized Crime Investigation 1 with Legal Medicine",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CRIM 105",
                "course" => "Juvenile Delinquency and Juvenile Justice System",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CRIM 106",
                "course" => "Criminological Research 1 (Research Methods with Applied Statistics)",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "DEF TACT 103",
                "course" => "First Aid and Water Safety",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "LEA 104",
                "course" => "Introduction to Industrial Security Concepts",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "FORENSIC 103",
                "course" => "Forensic Chemistry and Toxicology",
                "unit" => "5",
                "lecture" => "3",
                "laboratory" => "2",
            ],
            [
                "code" => "CLJ 104",
                "course" => "Criminal Evidence",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CDI 105",
                "course" => "Traffic Management and Accident Investigation with Driving",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CRIM 107",
                "course" => "Criminological Research 2 (Thesis Writing and Presentation)",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CRIM 108",
                "course" => "Dispute Resolution and Crises\/ Incidents Management",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "DEF TACT 104",
                "course" => "Fundamentals of Marksmanship",
                "unit" => "2",
                "lecture" => "2",
                "laboratory" => "0",
            ],
            [
                "code" => "OJT",
                "course" => "On-the-Job Training & Community Immersion (270 hrs.)",
                "unit" => "3",
                "lecture" => "0",
                "laboratory" => "0",
            ],
            [
                "code" => "CFLM 101",
                "course" => "Character Formation 1 - Nationalism and Patriotism",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CA 103",
                "course" => "Therapeutic Modalities",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "FORENSIC 104",
                "course" => "Forensic Ballistics",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "1",
            ],
            [
                "code" => "FORENSIC 105",
                "course" => "Questioned Document Examination",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "1",
            ],
            [
                "code" => "CLJ 105",
                "course" => "Criminal Procedure and Court Testimony",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CDI 106",
                "course" => "Specialized Crime Investigation 2 with Simulation on Interrogation and Interview",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CDI 107",
                "course" => "Vice and Drug Education and Control",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CFLM 102",
                "course" => "Character Formation 2 - Leadership, Decision Making, Management and Administration",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CLJ 106",
                "course" => "Human Rights Education",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "FORENSIC 106",
                "course" => "Lie Detection Techniques",
                "unit" => "3",
                "lecture" => "2",
                "laboratory" => "1",
            ],
            [
                "code" => "CDI 108",
                "course" => "Fire Technology and Arson Investigation",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CDI 109",
                "course" => "Introduction to Cybercrime and Environmental Laws and Protection",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "CRIM 109",
                "course" => "Professional Practice & Review with Comprehensive Examination",
                "unit" => "6",
                "lecture" => "6",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 101",
                "course" => "The Child and Adolescent Learners and Learning Principles ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 111",
                "course" => "History of Mathematics ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 112",
                "course" => "College and Advanced Algebra ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Litr 101",
                "course" => "Sosyedad at Literatura\/Panitikang Panlipunan ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 102",
                "course" => "The Teaching Profession ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 121",
                "course" => "Trigonometry ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 122",
                "course" => "Plane and Solid Geometry ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 123",
                "course" => "Logic and Set Theory ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 103",
                "course" => "The Teacher and the Community, School Culture and Organizational Leadership ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 104",
                "course" => "Assessment in Learning 1 ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 105",
                "course" => "Facilitating Learner-Centered Teaching ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 211",
                "course" => "Modern Geometry ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 212",
                "course" => "Calculus 1 with Analytical Geometry ",
                "unit" => "4",
                "lecture" => "4",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 213",
                "course" => "Elementary Statistics and Probability ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 106",
                "course" => "Foundation of Special and Inclusive Education ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 107",
                "course" => "Technology for Teaching and Learning 1 ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 108",
                "course" => "The Teacher and the School Curriculum ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 221",
                "course" => "Calculus 2 ",
                "unit" => "4",
                "lecture" => "4",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 222",
                "course" => "Linear Algebra ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Fili 103",
                "course" => "Retorika at Masining na Pagpapahayag ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 109",
                "course" => "Assessment in Learning 2 ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 110",
                "course" => "Building and Enhancing New Literacies Across the Curriculum ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 311",
                "course" => "Calculus 3 ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 312",
                "course" => "Advanced Statistics ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 313",
                "course" => "Principles and Strategies in Teaching Mathematics ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 314",
                "course" => "Problem Solving, Mathematical Investigation and Modeling ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 315",
                "course" => "Research in Mathematics 1",
                "unit" => "4",
                "lecture" => "4",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 321",
                "course" => "Technology Application in Mathematics Teaching ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 322",
                "course" => "Assessment and Evaluation in Mathematics ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 323",
                "course" => "Mathematics of Investment ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 324",
                "course" => "Abstract Algebra ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 325",
                "course" => "Number Theory ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 326",
                "course" => "Differential Equation ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "MEd 327",
                "course" => "Research in Mathematics 2 ",
                "unit" => "1",
                "lecture" => "1",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 111",
                "course" => "Field Study 1 ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 112",
                "course" => "Field Study 2 ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 113",
                "course" => "Management of Students’ Behavior and Wellness ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 114",
                "course" => "Special Topics in Education ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 115",
                "course" => "Teaching Internship ",
                "unit" => "6",
                "lecture" => "6",
                "laboratory" => "0",
            ],
            [
                "code" => "Ed 116",
                "course" => "Comprehensive Examination ",
                "unit" => "3",
                "lecture" => "3",
                "laboratory" => "0",
            ],
        ];
    }
}
