#!/bin/bash
choice=${1:-0}

if ((choice == 0)); then
    echo "*****************************"
    echo "* [1] clear all             *"
    echo "* [2] clear storage disks   *"
    echo "* [3] migrate:fresh --seed  *"
    echo "* [4] del debugbar/*.json   *"
    echo "* [5] artisan serve         *"
    echo "*****************************"
    read -p "Enter choice: " choice
fi

if (( $choice == "1" )); then
    echo "> artisan cache:clear --------------------"
    php artisan cache:clear

    echo "> artisan view:clear ---------------------"
    php artisan view:clear

    echo "> artisan config:cache -------------------"
    php artisan config:clear

    echo "> artisan route:clear --------------------"
    php artisan route:clear

    echo "> rm -r storage/debugbar/*.json ----------"
    rm -r storage/logs/*.log

elif (( $choice == "2" )); then
    echo "> deleting app/files ---------------------"
    rm -r storage/app/files/*

    echo "> deleting app/livewire-tmp --------------"
    rm -r storage/app/livewire-tmp/*

elif (( $choice == "3" )); then
    echo "> migrate:fresh --seed -------------------"
    php artisan migrate:fresh --seed

elif (( $choice == "4" )); then
    echo "> rm -r storage/debugbar/*.json ----------"
    rm -r storage/debugbar/*.json

elif (( $choice == "5" )); then
    echo "> artisan serve --------------------------"
    php artisan serve --host='localhost' --port='8009'

fi